-- LinguaFlip — Supabase seed data
-- Run this once in the Supabase SQL editor after running schema.sql.
-- Uses `on conflict (id) do nothing` so the file is safe to re-run.

insert into public.words (id, english, indonesian) values
  (1, 'Good morning', 'Selamat pagi'),
  (2, 'Good afternoon', 'Selamat siang'),
  (3, 'Good evening', 'Selamat malam'),
  (4, 'Hello', 'Halo'),
  (5, 'Goodbye', 'Selamat tinggal'),
  (6, 'See you later', 'Sampai jumpa'),
  (7, 'Thank you', 'Terima kasih'),
  (8, 'You''re welcome', 'Sama-sama'),
  (9, 'Please', 'Tolong'),
  (10, 'Sorry', 'Maaf'),
  (11, 'Yes', 'Ya'),
  (12, 'No', 'Tidak'),
  (13, 'Maybe', 'Mungkin'),
  (14, 'Excuse me', 'Permisi'),
  (15, 'I / Me', 'Saya'),
  (16, 'You', 'Anda / Kamu'),
  (17, 'He / She', 'Dia'),
  (18, 'We', 'Kami / Kita'),
  (19, 'They', 'Mereka'),
  (20, 'Friend', 'Teman'),
  (21, 'Family', 'Keluarga'),
  (22, 'Mother', 'Ibu'),
  (23, 'Father', 'Bapak / Ayah'),
  (24, 'Child', 'Anak'),
  (25, 'Man', 'Pria'),
  (26, 'Woman', 'Wanita'),
  (27, 'One', 'Satu'),
  (28, 'Two', 'Dua'),
  (29, 'Three', 'Tiga'),
  (30, 'Four', 'Empat'),
  (31, 'Five', 'Lima'),
  (32, 'Six', 'Enam'),
  (33, 'Seven', 'Tujuh'),
  (34, 'Eight', 'Delapan'),
  (35, 'Nine', 'Sembilan'),
  (36, 'Ten', 'Sepuluh'),
  (37, 'Hundred', 'Seratus'),
  (38, 'Thousand', 'Seribu'),
  (39, 'Today', 'Hari ini'),
  (40, 'Tomorrow', 'Besok'),
  (41, 'Yesterday', 'Kemarin'),
  (42, 'Now', 'Sekarang'),
  (43, 'Later', 'Nanti'),
  (44, 'Morning', 'Pagi'),
  (45, 'Afternoon', 'Siang'),
  (46, 'Evening', 'Malam'),
  (47, 'Week', 'Minggu'),
  (48, 'Month', 'Bulan'),
  (49, 'Year', 'Tahun'),
  (50, 'Hour', 'Jam'),
  (51, 'Minute', 'Menit'),
  (52, 'Here', 'Di sini'),
  (53, 'There', 'Di sana'),
  (54, 'Home', 'Rumah'),
  (55, 'Hotel', 'Hotel'),
  (56, 'Restaurant', 'Restoran'),
  (57, 'Hospital', 'Rumah sakit'),
  (58, 'Market', 'Pasar'),
  (59, 'Beach', 'Pantai'),
  (60, 'Airport', 'Bandara'),
  (61, 'Street', 'Jalan'),
  (62, 'City', 'Kota'),
  (63, 'Village', 'Desa'),
  (64, 'Food', 'Makanan'),
  (65, 'Water', 'Air'),
  (66, 'Rice', 'Nasi'),
  (67, 'Chicken', 'Ayam'),
  (68, 'Fish', 'Ikan'),
  (69, 'Vegetables', 'Sayuran'),
  (70, 'Fruit', 'Buah'),
  (71, 'Coffee', 'Kopi'),
  (72, 'Tea', 'Teh'),
  (73, 'Delicious', 'Enak'),
  (74, 'Hot', 'Panas'),
  (75, 'Cold', 'Dingin'),
  (76, 'Car', 'Mobil'),
  (77, 'Bus', 'Bus'),
  (78, 'Motorbike', 'Motor'),
  (79, 'Taxi', 'Taksi'),
  (80, 'Ticket', 'Tiket'),
  (81, 'Map', 'Peta'),
  (82, 'Left', 'Kiri'),
  (83, 'Right', 'Kanan'),
  (84, 'Straight', 'Lurus'),
  (85, 'Far', 'Jauh'),
  (86, 'Near', 'Dekat'),
  (87, 'Expensive', 'Mahal'),
  (88, 'Cheap', 'Murah'),
  (89, 'To eat', 'Makan'),
  (90, 'To drink', 'Minum'),
  (91, 'To go', 'Pergi'),
  (92, 'To come', 'Datang'),
  (93, 'To want', 'Mau / Ingin'),
  (94, 'To need', 'Perlu'),
  (95, 'To have', 'Punya'),
  (96, 'To see', 'Lihat'),
  (97, 'To hear', 'Dengar'),
  (98, 'To speak', 'Bicara'),
  (99, 'To understand', 'Mengerti'),
  (100, 'To know', 'Tahu'),
  (101, 'To like', 'Suka'),
  (102, 'To love', 'Cinta / Sayang'),
  (103, 'To buy', 'Beli'),
  (104, 'To sell', 'Jual'),
  (105, 'To work', 'Kerja'),
  (106, 'To sleep', 'Tidur'),
  (107, 'To wake up', 'Bangun'),
  (108, 'To help', 'Bantu'),
  (109, 'To open', 'Buka'),
  (110, 'To close', 'Tutup'),
  (111, 'To wait', 'Tunggu'),
  (112, 'To stop', 'Berhenti'),
  (113, 'Big', 'Besar'),
  (114, 'Small', 'Kecil'),
  (115, 'Good', 'Bagus / Baik'),
  (116, 'Bad', 'Buruk / Jelek'),
  (117, 'New', 'Baru'),
  (118, 'Old', 'Lama / Tua'),
  (119, 'Fast', 'Cepat'),
  (120, 'Slow', 'Lambat'),
  (121, 'Easy', 'Mudah'),
  (122, 'Difficult', 'Sulit'),
  (123, 'Beautiful', 'Cantik / Indah'),
  (124, 'Happy', 'Senang / Bahagia'),
  (125, 'Sad', 'Sedih'),
  (126, 'Tired', 'Lelah / Capek'),
  (127, 'Sick', 'Sakit'),
  (128, 'Healthy', 'Sehat'),
  (129, 'Safe', 'Aman'),
  (130, 'Busy', 'Sibuk'),
  (131, 'Free', 'Bebas / Gratis'),
  (132, 'Ready', 'Siap'),
  (133, 'What', 'Apa'),
  (134, 'Who', 'Siapa'),
  (135, 'Where', 'Di mana'),
  (136, 'When', 'Kapan'),
  (137, 'Why', 'Kenapa / Mengapa'),
  (138, 'How', 'Bagaimana'),
  (139, 'How much', 'Berapa'),
  (140, 'Which', 'Yang mana'),
  (141, 'I don''t understand', 'Saya tidak mengerti'),
  (142, 'I don''t know', 'Saya tidak tahu'),
  (143, 'Can you help me?', 'Bisa bantu saya?'),
  (144, 'How much does this cost?', 'Ini berapa harganya?'),
  (145, 'Where is the toilet?', 'Di mana toilet?'),
  (146, 'I want this', 'Saya mau ini'),
  (147, 'Speak slowly please', 'Tolong bicara pelan-pelan'),
  (148, 'What is your name?', 'Siapa nama Anda?'),
  (149, 'My name is...', 'Nama saya...'),
  (150, 'Nice to meet you', 'Senang bertemu Anda'),
  (151, 'I am from Australia', 'Saya dari Australia'),
  (152, 'Do you speak English?', 'Anda bisa berbahasa Inggris?'),
  (153, 'Red', 'Merah'),
  (154, 'Blue', 'Biru'),
  (155, 'Green', 'Hijau'),
  (156, 'Yellow', 'Kuning'),
  (157, 'White', 'Putih'),
  (158, 'Black', 'Hitam'),
  (159, 'Head', 'Kepala'),
  (160, 'Hand', 'Tangan'),
  (161, 'Eye', 'Mata'),
  (162, 'Mouth', 'Mulut'),
  (163, 'Heart', 'Hati / Jantung'),
  (164, 'Foot', 'Kaki'),
  (165, 'Rain', 'Hujan'),
  (166, 'Sun', 'Matahari'),
  (167, 'Wind', 'Angin'),
  (168, 'Mountain', 'Gunung'),
  (169, 'Sea', 'Laut'),
  (170, 'River', 'Sungai'),
  (171, 'Tree', 'Pohon'),
  (172, 'Flower', 'Bunga'),
  (173, 'Money', 'Uang'),
  (174, 'Book', 'Buku'),
  (175, 'Phone', 'Telepon / HP'),
  (176, 'Door', 'Pintu'),
  (177, 'Window', 'Jendela'),
  (178, 'Table', 'Meja'),
  (179, 'Chair', 'Kursi'),
  (180, 'Bag', 'Tas'),
  (181, 'Clothes', 'Baju / Pakaian'),
  (182, 'Shoes', 'Sepatu'),
  (183, 'To read', 'Membaca'),
  (184, 'To write', 'Menulis'),
  (185, 'To give', 'Memberi'),
  (186, 'To take', 'Mengambil'),
  (187, 'To run', 'Berlari'),
  (188, 'To walk', 'Berjalan'),
  (189, 'To sit', 'Duduk'),
  (190, 'To stand', 'Berdiri'),
  (191, 'I''m hungry', 'Saya lapar'),
  (192, 'I''m thirsty', 'Saya haus'),
  (193, 'It''s okay', 'Tidak apa-apa'),
  (194, 'Let''s go', 'Ayo pergi'),
  (195, 'Be careful', 'Hati-hati'),
  (196, 'No problem', 'Tidak masalah'),
  (197, 'Of course', 'Tentu saja'),
  (198, 'I agree', 'Saya setuju'),
  (199, 'Welcome', 'Selamat datang'),
  (200, 'Congratulations', 'Selamat')
on conflict (id) do nothing;
